services:
  backend:
    build: .
    container_name: filesense_backend
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db_data:/app/chroma_db_data
    env_file:
      - .env
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: .
    container_name: filesense_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    command: ["uv", "run", "streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]