
services:
  #Backend API
  backend:
    build: .
    container_name: ragnite_backend
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db_data:/app/chroma_db_data  
    env_file:
      - .env

  #Frontend UI
  frontend:
    build: .
    container_name: ragnite_frontend
    ports:
      - "8501:8501"
    command: ["uv", "run", "streamlit", "run", "frontend/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
    environment:
      - API_URL=http://backend:8000/api/v1  
    depends_on:
      - backend